default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: epify_development

test:
  <<: *default
  database: epify_test

production:
  <<: *default
  database: epify_production
